### ISSUE TITLE
replay proxy doesn't start because of sw.js file not found

### ISSUE THREAD

**Issue by mbreevoort** [iipc/jwarc#57]
Thanks for the great project.
When I try to serve a warc I get the following error:
```
java -jar jwarc.jar serve mywarc.warc
Exception in thread "main" java.nio.file.NoSuchFileException: sw.js
	at org.netpreserve.jwarc.net.WarcServer.resource(WarcServer.java:202)
	at org.netpreserve.jwarc.net.WarcServer.<init>(WarcServer.java:52)
	at org.netpreserve.jwarc.net.WarcServer.<init>(WarcServer.java:45)
	at org.netpreserve.jwarc.tools.ServeTool.main(ServeTool.java:21)
	at org.netpreserve.jwarc.tools.WarcTool.main(WarcTool.java:47)
```

The files sw.js and inject.js are in `resources/org/netpreserve/net/`
Because the resources are relative resolved in `WarcServer` they are expected in `resouces/org/netpreserve/jwarc/net/` or use absolute path `/org/netpreserve/net/` in `WarcServer` to resolve the resource.

jwarc version 0.13.1
java 11 and 15

**Comment by ato** [comment]
Thanks for reporting this. I incorrectly moved those files when refactoring. Fix released as v0.14.0.
