### ISSUE TITLE
URIs.parseLeniently fails to parse WARC-Target-URI with query and empty path with no slash before query

### ISSUE THREAD

**Issue by sebastian-nagel** [iipc/jwarc#90]
The method `URIs.parseLeniently(String uri)` fails on a WARC-Target-URI which is a valid URI with a query part (starting with `?`) but no (or empty) path part (and no path root `/`).

Example: `https://secur-serv.com?post_type=post&categories[]=8`

```
Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in hostname at index 22: https://secur-serv.com%3Fpost_type=post&categories[]=8
        at org.netpreserve.jwarc.URIs.parseLeniently(URIs.java:36)
        at org.netpreserve.jwarc.WarcTargetRecord.targetURI(WarcTargetRecord.java:48)
```

Sure, the URL could be normalized to `https://secur-serv.com/?post_type=post&categories[]=8`. However, even without normalization, it's both a valid URI and URL, parseable and fetchable:

```jshell
jshell> URI uri = new URI("https://secur-serv.com?post_type=post&categories[]=8")
uri ==> https://secur-serv.com?post_type=post&categories[]=8

jshell> URL url = new URL("https://secur-serv.com?post_type=post&categories[]=8")
url ==> https://secur-serv.com?post_type=post&categories[]=8

jshell> uri.getPath()
$11 ==> ""

jshell> url.getPath()
$12 ==> ""

jshell> uri.getQuery()
$13 ==> "post_type=post&categories[]=8"

jshell> url.getQuery()
$14 ==> "post_type=post&categories[]=8"

jshell> url.toURI()
$15 ==> https://secur-serv.com?post_type=post&categories[]=8

jshell> uri.toString()
$17 ==> "https://secur-serv.com?post_type=post&categories[]=8"

jshell> url.toString()
$18 ==> "https://secur-serv.com?post_type=post&categories[]=8"

jshell> byte[] content = url.openStream().readAllBytes()
content ==> byte[71475] { 60, 33, 68, 79, 67, 84, 89, 80, 69, ... , 104, 116, 109, 108, 62 }

jshell> new String(content).split("\n")[14]
$24 ==> "\t<title>Search Results for &#8220;&#8221; &#8211; Secur-Serv</title>"
```

**Comment by sebastian-nagel** [comment]
Detected along with #91, by looking at URIs (all taken from a WARC-Target-URI) for which a round trip parsing / conversion failed:
- if the query does not contain characters not allowed in the authority part of the URI, there is not exception but the authority then contains the quotation mark which is percent-encoded in the string representation or when converting to an URL:
  ```
  jshell> URI uri = URIs.parseLeniently("https://db-events.eu?lang=en")
  uri ==> https://db-events.eu%3Flang=en

  jshell> uri.getAuthority()
  $9 ==> "db-events.eu?lang=en"

  jshell> uri.toURL()
  $10 ==> https://db-events.eu%3Flang=en

  jshell> uri.toURL().getHost()
  $11 ==> "db-events.eu%3Flang=en"
  ```
- same for queries with no path but a fragment:
  ```
  jshell> URIs.parseLeniently("https://www.bruessel-wein.de#kontakt")
  $12 ==> https://www.bruessel-wein.de%23kontakt
  ```
